In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
def get_targets(path: str):
    df = pd.read_csv(os.path.join(path, "train.csv"), engine="python")
    targets = df["Pawpularity"].copy().values
    return targets

In [3]:
targets = get_targets("../input/petfinder-pawpularity-score")

targets[:5]

array([63, 42, 28, 15, 72])

In [4]:
classify_targets = targets.copy()

classify_targets[np.logical_and(targets >= 1, targets < 11)] = 0
classify_targets[np.logical_and(targets >= 11, targets < 21)] = 1
classify_targets[np.logical_and(targets >= 21, targets < 31)] = 2
classify_targets[np.logical_and(targets >= 31, targets < 41)] = 3
classify_targets[np.logical_and(targets >= 41, targets < 51)] = 4
classify_targets[np.logical_and(targets >= 51, targets < 61)] = 5
classify_targets[np.logical_and(targets >= 61, targets < 71)] = 6
classify_targets[np.logical_and(targets >= 71, targets < 81)] = 7
classify_targets[np.logical_and(targets >= 81, targets < 91)] = 8
classify_targets[np.logical_and(targets >= 91, targets < 100)] = 9

classify_targets[:5]

array([6, 4, 2, 1, 7])

In [5]:
regress_targets = targets.copy()
regress_targets = regress_targets % 10

regress_targets[:5]

array([3, 2, 8, 5, 2])